version: 2
updates:
  - package-ecosystem: "mix" # for Elixir dependencies
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "phoenix-contrib/storage-maintainers"
    assignees:
      - "phoenix-contrib/storage-maintainers"
    commit-message:
      prefix: "deps"
      include: "scope"
  
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    reviewers:
      - "phoenix-contrib/storage-maintainers"
    assignees:
      - "phoenix-contrib/storage-maintainers"
    commit-message:
      prefix: "ci"
      include: "scope"